"""empty message

Revision ID: 0c594e164797
Revises: 726e54ae7b40
Create Date: 2026-02-25 02:35:44.499639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c594e164797'
down_revision = '726e54ae7b40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planetasfavoritos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usersw_id', sa.Integer(), nullable=False),
    sa.Column('planetas_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['planetas_id'], ['planetas.id'], ),
    sa.ForeignKeyConstraint(['usersw_id'], ['usersw.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('planetasfavoritos')
    # ### end Alembic commands ###
