"""empty message

Revision ID: 726e54ae7b40
Revises: 493c8501cb9b
Create Date: 2026-02-25 02:31:15.667518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '726e54ae7b40'
down_revision = '493c8501cb9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personajesfavoritos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usersw_id', sa.Integer(), nullable=False),
    sa.Column('personajes_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['personajes_id'], ['personajes.id'], ),
    sa.ForeignKeyConstraint(['usersw_id'], ['usersw.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('personajesfavoritos')
    # ### end Alembic commands ###
