"""empty message

Revision ID: 8192118f6741
Revises: 0c594e164797
Create Date: 2026-02-25 02:40:09.249037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8192118f6741'
down_revision = '0c594e164797'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('navesfavoritas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usersw_id', sa.Integer(), nullable=False),
    sa.Column('naves_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['naves_id'], ['naves.id'], ),
    sa.ForeignKeyConstraint(['usersw_id'], ['usersw.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('navesfavoritas')
    # ### end Alembic commands ###
